AWSTemplateFormatVersion: 2010-09-09
Description: App Runner service

Parameters:
  Image:
    Type: String
    Description: ECR container image
  AutoScalingConfigArn:
    Type: String
    Description: Auto scaling configuration ARN

Resources:
  AccessRole: 
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: nim-app-access-role
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal: 
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
  Service: 
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: nim-app
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AccessRole.Arn
        AutoDeploymentsEnabled: true
        ImageRepository:
          ImageIdentifier: !Ref Image
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: 8080
      InstanceConfiguration:
        Cpu: 1 vCPU
        Memory: 2 GB
      HealthCheckConfiguration:
        Path: /health
        Protocol: HTTP
      AutoScalingConfigurationArn: !Ref AutoScalingConfigArn

Outputs:
  Arn:
    Description: Service ARN
    Value: !GetAtt Service.ServiceArn
  Url:
    Description: Service URL
    Value: !GetAtt Service.ServiceUrl
